### ISSUE TITLE
emit2, emit3, ..., emitWithCallback,emit2WithCallback

### ISSUE THREAD

**Issue by danneu** [mgold/elm-socketio#2]
To learn more Elm, today I used elm-socketio to write a chat client that could handle various socket.io chat APIs I've seen or built over the years.

The first thing I needed was more arity options for `emit` so that I had an analogue for these example signatures:

``` javascript
socket.emit('new_message', text, username);
socket.emit('new_message', text, username, channel);
socket.emit('new_message', text, username, channel, isPrivate);
```

Seems to me that the Elm way to handle this is to expose `emit2`, `emit3`, `emit4`, etc.

---

The next thing I needed was the ability to handle the conventional `fn(err [, result])` callback that some APIs expect.

``` javascript
socket.emit('new_message', text, function(err) {
  if (err) {
    // message rejected by server
    // err is one of 'USER_IS_MUTED' | 'INTERNAL_ERROR' | 'INVALID_COMMAND' | ...
    return;
  }
  // else message was accepted by server and we are free to clear
  // the input box for user to type their next message
});
```

I'm new to Elm, but I decided to roll a function `emitWithCallback` which takes a function after the message arguments that will get passed a `(Result Left Right)` of the server's response to
the callback.

Here's my implementation, to see what I'm talking about:

``` elm
// in src/Native/SocketIO.elm
var Result = Elm.Result.make(localRuntime);

function emitWithCallback(eventName, message, cb, socket) {
  return Task.asyncFunction(function(elmback) {
    if (socket.disconnected) return elmback(Task.fail('Socket disconnected'));
    if (eventName === '') {
      socket.send(message);
    } else {
      socket.emit(eventName, message, function(left, right) {
        if (left) {
          return elmback(Task.succeed(cb(Result.Err(left))));
        } else {
          return elmback(Task.succeed(cb(Result.Ok(right))));
        }
      });
    }
  });
}
```

Here's the signature:

``` elm
emitWithCallback : String -> String -> (Result a b -> c) -> Socket -> Task.Task x c
emitWithCallback =
  Native.MySocketIO.emitWithCallback
```

And here's how I used it to return an `Effects Action` so I could
perceive the result in my update function:

``` elm
type SubmitMessageError
  = UserIsMuted
  | InternalError
  | Forbidden
  | InvalidCommand
  --
  | UnknownError

sendMessage : ChatInput.Model -> Effects Action
sendMessage text =
  getSocket
  `andThen` (\socket ->
    let
      callback : Result String x -> Result SubmitMessageError ()
      callback result =
        case result of
          Err err ->
            case err of
              "INVALID_COMMAND" ->
                Err InvalidCommand
              "USER_IS_MUTED" ->
                Err UserIsMuted
              "INTERNAL_ERROR" ->
                Err InternalError
              "FORBIDDEN" ->
                Err Forbidden
              _ ->
                Err UnknownError
          Ok _ ->
             Ok ()
    in
      MySocketIO.emitWithCallback "new_message" text callback socket
  )
  |> Effects.task
  |> Effects.map HandleSubmitMessageResponse
```

Once again, I'm a noob and I'm just trying to demonstrate my use case and
what worked for me.

This sort of callback is common in socket.io APIs I've worked with because
it allows you to do things like easily perceive back-pressure or
explicitly handle a message receipt (like view validation errors like
'USERNAME_TAKEN' or whether the message was persisted to the database). 

Though I'm not sure how to make it more general or if it's not general enough.

----

And then I needed the ability to emit multiple arguments along with a
callback to handle the response.

``` javascript
socket.emit('new_message', text, username, cb);
socket.emit('new_message', text, username, channel, cb);
socket.emit('new_message', text, username, channel, isPrivate, cb);
```

Where `emit2WithCallback`, `emit3WithCallback`, etc. would solve it.

----

Finally, I needed more arity options for `on` handlers to mirror `emit2`, `emit3`, etc.

For example, support for handlers like:

``` javascript
socket.on('user_muted', username, duration, handler);
```

----

What do you think?

**Comment by mgold** [comment]
First, this library pretty much assumes that you control that socket.io server, and can therefore define an API that works with Elm – rather than make Elm work with an API. There are certain things that just aren't type-safe or immutable (like joining a room or passing N arguments), and if you need to do them, do them in JavaScript and then pass the cleaned-up values in through a port.

There's really no difference between passing N arguments and passing a JSON object or array. Elm's Json.Encode and Json.Decode libraries work quite well for the case of sending multiple things per event.

Every time you call `on` or `emit`, you have to use `Task.andThen` to get the socket. The dirty secret here is that this reruns the task, but, [the socket will not be recreated and if it's connected, is immediately returned](https://github.com/mgold/elm-socketio/blob/f439904053fb829025dabbc98d6ca34b190885e2/src/Native/SocketIO.js#L17-L19). The socket will not be returned (the task will not succeed) until it is connected. If the socket never connects, the task will neither succeed not fail, and anything chained to it with `Task.andThen` will not run. Therefore, the odds that `emit` will fail are small, since you just verified that the socket was connected.

I don't know what APIs you are referring to in the second code block with define `emit` taking a callback. In the Socket.io client, [emit does not take a callback](http://socket.io/docs/server-api/#socket#emit(name:string[,-…]):socket). Instead it looks like they will try to send the function itself, but fail since it's not serializable. Since your error handling stems from the errors defined in that second code block that I don't know where it came from, I also don't understand the value of a callback for `emit`. As I just explained, connection errors rarely make it to `emit`. The socket will attempt to reconnect automatically (depending on the `Options` it was passed). So I don't see the value of error handling or callbacks on `emit`; it is purely an effect, which is what the type `task x ()` conveys. (It's a task that produces `()`, which is useless, so it must have an effect instead.)

If there's an error at the level of your API, then that should be reflected in the payload, not socket-level error handling.

Because everything in this library is a task, you can easily promote them to effects. I don't want to make `elm-effects` a dependency if I don't have to.

**Comment by danneu** [comment]
So, to be clear, elm-socketio's intended scope is limited to clients talking to APIs that you've defined, and where all parts of the API only have 1 payload argument, and where clients cannot register callbacks for the server to communicate back with? That sounds reasonable when the only socket.io features both sides care about is the reconnection logic and similar conveniences.

Regards to `emit` not taking a callback argument, you linked to the Server API. Though the [http://socket.io/docs/client-api/](Client API) doesn't even mention any of the socket methods at all much less their signatures. But socket.io's docs have always been that bad.

I don't know how the client-side callback system is implemented, but it does tell the server that you provided one. I wouldn't even be surprised if you could call `callback.toString()` on the server given other peculiarities in the socket.io API.

But this does work and is a common pattern in websocket APIs:

``` javascript
// server
clientSocket.on('new_message', function(text, clientCallback) {
    if (isMuted user) {
      if (clientCallback) clientCallback('USER_MUTED');
      return;
    }
    // success
    if (clientCallback) clientCallback();
})

// client
socket.emit('new_message', 'hello world', function(err) {
  if (err === 'USER_MUTED') { 
    ...
  }
});
```

> If there's an error at the level of your API, then that should be reflected in the payload, not socket-level error handling.

How else would you consume this error response payload from the server that you're talking to with websockets? Filter the matching response back out of some global response bus? That's what Socket.io is already doing for you here.

Finally, I'm not trying to handle technical socket errors in my example. That's why both branches end on `Task.succeed(Err)` and `Task.succeed(Ok)` - the task/emit succeeded, and I'm trying to then perceive the higher-level domain-level error from the server like "USER_IS_MUTED" or if there was no error at all. For the same reason you don't want to handle 200 vs 400 server responses at the same abstraction level or location that you handle the case where the network is unavailable to begin with.

Maybe my implementation could be done better but that's the spirit of it what it was trying to achieve.

I didn't understand your bit about elm-effects. The only reason it showed up in the code above was because the snippet was extracted from an actual StartApp app.

**Comment by mgold** [comment]
>scope is limited to clients talking to APIs that you've defined

When I wrote it, the use case I had in mind was "I need Elm to talk to a database/filesystem/Raspberry Pi and don't really care how that happens". Due to the single-origin policy, it's rare to communicate with public servers in Elm, and most APIs are HTTP.

> where all parts of the API only have 1 payload argument

Again, if you write the API yourself, this isn't a problem. Variadic functions aren't a thing in Elm the way they are in JavaScript; the only way to fake it is to accept a list. Which would make the common case of one payload argument clunky. Although it's true that a careful reading of the (server!) docs indicate that any number of arguments are allowed, I've never seen that in examples.

> where clients cannot register callbacks for the server to communicate back with

Again, this is a feature I have never seen used or documented. Furthermore, Elm's approach to callbacks is different from JavaScript's. The server communicates with the client when *it* emits an event, not the client. Building an API on an error field in a callback that isn't documented is just ridiculous.

> That sounds reasonable when the only socket.io features both sides care about is the reconnection logic and similar conveniences.

Some socket.io features, such as rooms, involve mutating the socket that may be shared in other places. This is not acceptable in Elm. *As stated in the README*, if you need advanced features, use JavaScript. You can use ports to pass in Elm values; you do not need another library.

The only possible *useful* thing that you could contribute to this discussion is concrete use case, a public socket.io API. But you haven't done so in two posts, so it's not worth the aggravation.
